motor_driver:
  ros__parameters:
    deadband: 0.002
    max_abs_speed: 0.40

    left_motor:
      phase_pin: 20
      enable_pin: 21
      inverted: false

    right_motor:
      phase_pin: 23
      enable_pin: 24
      inverted: false