motor_driver:
  ros__parameters:
    deadband: 0.002
    max_abs_effort: 0.60

    left_motor:
      phase_pin: 20
      enable_pin: 21
      inverted: false

    right_motor:
      phase_pin: 23
      enable_pin: 24
      inverted: false

imu:
  ros__parameters:
    i2c_address: 74  # 0x4A
    i2c_frequency_hz: 400000
    publish_rate_hz: 20.0

wheel_state:
  ros__parameters:
    # the left encoder is on /dev/i2c-2 and the right encoder is on /dev/i2c-1.
    left_sensor_bus: 2
    right_sensor_bus: 1
    gear_ratio: 7.0
    publish_rate_hz: 20.0
